BEGIN WORK;
DROP TABLE IF EXISTS reviews;


CREATE TABLE reviews(
   movieId    INTEGER  NOT NULL PRIMARY KEY 
  ,metascore  VARCHAR(5)
  ,boxOffice  VARCHAR(15)
  ,website    VARCHAR(44)
  ,imdbRating NUMERIC(3,1)
  ,imdbVotes  VARCHAR(9)
  ,runtime    VARCHAR(7)
  ,language   VARCHAR(33)
  ,rated      VARCHAR(9)
  ,production VARCHAR(33)
  ,released   DATE 
  ,imdbid     VARCHAR(9)
  ,plot       VARCHAR(239)
  ,director   VARCHAR(40)
  ,title      VARCHAR(36) NOT NULL
  ,actors     VARCHAR(78)
  ,response   VARCHAR(4)
  ,type       VARCHAR(5)
  ,awards     VARCHAR(64)
  ,dvd        DATE 
  ,year       INTEGER 
  ,poster     VARCHAR(159)
  ,country    VARCHAR(40)
  ,genre      VARCHAR(44)
  ,writer     VARCHAR(500)
);

INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (1,'67','$389,804,217','https://marvel.com/guardians',7.7,'449,175','136 min','English','PG-13','Walt Disney Pictures','05 May 2017','tt3896198','The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord''s encounter with his father the ambitious celestial being Ego.','James Gunn','Guardians of the Galaxy Vol. 2','Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel','True','movie','Nominated for 1 Oscar. Another 12 wins & 42 nominations.','22 Aug 2017',2017,'https://m.media-amazon.com/images/M/MV5BMTg2MzI1MTg3OF5BMl5BanBnXkFtZTgwNTU3NDA2MTI@._V1_SX300.jpg','USA','Action, Adventure, Comedy, Sci-Fi','James Gunn, Dan Abnett (based on the Marvel comics by), Andy Lanning (based on the Marvel comics by), Steve Englehart (Star-Lord created by), Steve Gan (Star-Lord created by), Jim Starlin (Gamora and Drax created by), Stan Lee (Groot created by), Larry Lieber (Groot created by), Jack Kirby (Groot created by), Bill Mantlo (Rocket Raccoon created by), Keith Giffen (Rocket Raccoon created by), Steve Gerber (Howard the Duck created by), Val Mayerik (Howard the Duck created by)');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (2,'90','N/A','http://www.starwars.com/episode-iv/',8.6,'1,104,701','121 min','English','PG','20th Century Fox','21 Sep 2004','tt0076759','Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire''s world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.','George Lucas','Star Wars: Episode IV - A New Hope','Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing','True','movie','Won 6 Oscars. Another 50 wins & 28 nominations.','25 May 1977',1977,'https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg','USA','Action, Adventure, Fantasy, Sci-Fi','George Lucas');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (3,'100','N/A','http://www.thegodfather.com',9.2,'1,408,749','175 min','English, Italian, Latin','R','Paramount Pictures','24 Mar 1972','tt0068646','The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.','Francis Ford Coppola','The Godfather','Marlon Brando, Al Pacino, James Caan, Richard S. Castellano','True','movie','Won 3 Oscars. Another 24 wins & 28 nominations.','09 Oct 2001',1977,'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg','USA','Crime, Drama','Mario Puzo (screenplay by), Francis Ford Coppola (screenplay by), Mario Puzo (based on the novel by)');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (33,'N/A','N/A','N/A',8.1,'26,541','3 min','None','G','Pixar Animation Studios','02 Nov 2001','tt0248808','A group of snooty birds roosting on a telephone wire get their just deserts when a goofy bird drops in.','Ralph Eggleston','For the Birds','Ralph Eggleston','True','movie','Won 1 Oscar. Another 5 wins & 2 nominations.',NULL,2000,'https://m.media-amazon.com/images/M/MV5BMTQzMDEyODYwNF5BMl5BanBnXkFtZTgwOTcxMDgwMjE@._V1_SX300.jpg','USA','Animation, Short, Comedy, Family','Ralph Eggleston');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (34,'N/A','N/A','N/A',8.5,'96','N/A','Afrikaans','N/A','N/A','25 Nov 2016','tt5799756','During the South African 70''s, a young nurse ruffles feathers as she shows a small town, and its golden boy, what it means to be an independent woman.','Quentin Krog','For the Birds','Simoné Nortmann, Francois Jacobs, Elize Cawood, Lara Kinnear','True','movie','N/A',NULL,2016,'https://images-na.ssl-images-amazon.com/images/M/MV5BZTkzM2M4NzctNGMyNy00ZGYzLTllODUtMGQ2NDc3NGJhMGJjL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTI5OTE5MjA@._V1_SX300.jpg','South Africa','Romance','Sean Robert Daniels, Quentin Krog, Tina Kruger');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (35,'N/A','N/A','N/A',6.9,'88','81 min','English','APPROVED','20th Century Fox Film Corporation','01 Oct 1952','tt0045173','Enviromentalist Anne Richards goes to Washington D. C. to fight for getting legislation passed to save the last remaining sanctuary of the almost-extinct California Condor. She enlists the ...','Robert Wise','Something for the Birds','Victor Mature, Patricia Neal, Edmund Gwenn, Larry Keating','True','movie','N/A',NULL,1952,'https://images-na.ssl-images-amazon.com/images/M/MV5BZGJiM2FhMmQtNzQ5NC00OWVkLWE2NmItZmMyZTFmZmY0OWVhXkEyXkFqcGdeQXVyNDY3MzU2MDM@._V1_SX300.jpg','USA','Comedy','Alvin M. Josephy (story and screenplay), Joseph Petracca (story and screenplay), Boris Ingster (story and screenplay)');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (36,'N/A','N/A','N/A',7.8,'22','14 min','Persian','N/A','N/A','24 Mar 2014','tt2978828','A crowd of people in Iran gather to watch the execution of a young girl. She cries and begs everyone for help. Horrified, people look away as the girl is about to get hanged, but one ...','Tara Atashgah','For the Birds','Nazli K. Lou, Chervine Namani, Kamran Malak Motiei, Leni Rico','True','movie','8 wins & 8 nominations.',NULL,2014,'http://ia.media-imdb.com/images/M/MV5BMTgyODc2ODg0NF5BMl5BanBnXkFtZTgwNjExMzgyMDE@._V1_SX300.jpg','USA','Short, Drama','Tara Atashgah');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (38,'N/A','N/A','N/A',8.0,'15','N/A','English','N/A','N/A','15 Jun 2018','tt2433118','A woman''s love for her pet ducks, chickens, geese, and turkeys - all 200 of them - ignites a battle with local animal rescuers and puts her marriage in jeopardy.','Richard Miron','For the Birds','N/A','True','movie','N/A',NULL,2018,'https://m.media-amazon.com/images/M/MV5BZTcyM2M5NDktODk4Yy00NDliLTliMjEtZjY3YTAwZWNiOWQxXkEyXkFqcGdeQXVyMTA1MTgzMjY@._V1_SX300.jpg','USA','Documentary, Drama','N/A');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (39,'N/A','N/A','N/A',3.4,'9','63 min','English','N/A','N/A','01 Nov 1963','tt0284522','N/A','Vernon Sewell','Strictly for the Birds','Tony Tanner, Joan Sims, Graham Stark, Jeanne Moody','True','movie','N/A',NULL,1963,'N/A','UK','Comedy','Tony Hawes');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (40,'N/A','N/A','N/A',9.9,'7','9 min','Romanian','N/A','N/A','11 Dec 2015','tt4935896','It''s been 70 years since the end of the Second World War and many stories about it have been told. We''ve heard about the Nazis, the Communists, the Americans, etc. But here is another one, ...','Ionut Necula','For the Birds','Teodor Necula, Livia Florea, Filip Nitescu, Octavian Rosu','True','movie','N/A',NULL,2015,'N/A','Romania','Short','Filip Nitescu (novel), Ionut Necula (screenplay)');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (41,'N/A','N/A','http://www.syfy.com/battlestar/',7.7,'19,604','101 min','English','Not Rated','Universal Pictures','24 Nov 2007','tt0991178','A two-hour Battlestar Galactica special that tells the story of the Battlestar Pegasus several months prior to it finding the Galactica.','Félix Enríquez Alcalá','Battlestar Galactica: Razor','Edward James Olmos, Mary McDonnell, Katee Sackhoff, Jamie Bamber','True','movie','1 win & 2 nominations.',NULL,2007,'https://m.media-amazon.com/images/M/MV5BMTk5MzUxNTYwMF5BMl5BanBnXkFtZTcwNTIyMjU1MQ@@._V1_SX300.jpg','USA','Action, Drama, Sci-Fi, Thriller','Ronald D. Moore (developed by), Michael Taylor, Glen A. Larson (based on the series created by: "Battlestar Galactica")');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (42,'N/A','N/A','N/A',7.1,'17,203','112 min','English','N/A','David Eick Productions','27 Oct 2009','tt1286130','When the initial Cylon attack against the Twelve Colonies fails to achieve complete extermination of human life as planned, twin Number Ones (Cavils) embedded on Galactica and Caprica must improvise to destroy the human survivors.','Edward James Olmos','Battlestar Galactica: The Plan','Edward James Olmos, Dean Stockwell, Michael Trucco, Grace Park','True','movie','1 nomination.',NULL,2009,'https://m.media-amazon.com/images/M/MV5BMTgyODE2MjY2OF5BMl5BanBnXkFtZTcwMjQxMTI5Mg@@._V1_SX300.jpg','USA','Action, Adventure, Drama, Romance, Sci-Fi','Jane Espenson');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (43,'N/A','N/A','N/A',7.0,'15,945','91 min','English','Unrated','Universal Pictures','09 Nov 2012','tt1704292','The adventures of young William Adama in the First Cylon War.','Jonas Pate','Battlestar Galactica: Blood & Chrome','Luke Pasqualino, Ben Cotton, Lili Bordán, Jill Teed','True','movie','Nominated for 3 Primetime Emmys. Another 3 wins & 3 nominations.',NULL,2012,'https://m.media-amazon.com/images/M/MV5BM2RiNjA4MzctMGU1MC00MThiLTk4OWUtODI4ZmM4MmU3YTllXkEyXkFqcGdeQXVyMDM0MzU2NA@@._V1_SX300.jpg','USA','Action, Sci-Fi','Michael Taylor (creator), David Eick (creator), Michael Taylor (teleplay), David Eick (story), Bradley Thompson (story), David Weddle (story), Glen A. Larson (creator: "Battlestar Galactica")');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (44,'N/A','N/A','N/A',7.1,'12,895','94 min','English','UNRATED','Universal Pictures','09 Nov 2012','tt1748706','The adventures of young William Adama in the First Cylon War.','Jonas Pate','Battlestar Galactica: Blood & Chrome','Luke Pasqualino, Ben Cotton, Lili Bordán, Jill Teed','True','movie','Nominated for 3 Primetime Emmys. Another 3 wins & 3 nominations.',NULL,2012,'http://ia.media-imdb.com/images/M/MV5BM2RiNjA4MzctMGU1MC00MThiLTk4OWUtODI4ZmM4MmU3YTllXkEyXkFqcGdeQXVyMDM0MzU2NA@@._V1_SX300.jpg','USA','Action, Sci-Fi','Michael Taylor (creator), David Eick (creator), Michael Taylor (teleplay), David Eick (story), Bradley Thompson (story), David Weddle (story), Glen A. Larson (creator: "Battlestar Galactica")');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (45,'N/A','N/A','N/A',6.8,'7,631','148 min','English','PG','MCA Universal Home Video','18 May 1979','tt0077215','After the destruction of the Twelve Colonies of Mankind, the last major fighter carrier leads a makeshift fugitive fleet in a desperate search for the legendary planet Earth.','Richard A. Colla, Alan J. Levi','Battlestar Galactica','Richard Hatch, Dirk Benedict, Lorne Greene, Herbert Jefferson Jr.','True','movie','N/A',NULL,1978,'https://m.media-amazon.com/images/M/MV5BYjhhYzBlZjktMmU2Ny00OTIyLThhZjctNTVjMGQxZWQyMzE4XkEyXkFqcGdeQXVyMzU4Nzk4MDI@._V1_SX300.jpg','USA','Action, Adventure, Sci-Fi','Glen A. Larson');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (46,'83','$83,775,048','http://www.TheUpInTheAirMovie.com/',7.4,'299,432','109 min','English','R','Paramount Pictures','23 Dec 2009','tt1193138','Ryan Bingham enjoys living out of a suitcase for his job, travelling around the country firing people, but finds that lifestyle threatened by the presence of a potential love interest, and a new hire.','Jason Reitman','Up in the Air','George Clooney, Vera Farmiga, Anna Kendrick, Jason Bateman','True','movie','Nominated for 6 Oscars. Another 76 wins & 158 nominations.',NULL,2009,'https://m.media-amazon.com/images/M/MV5BMTI3MzYxMTA4NF5BMl5BanBnXkFtZTcwMDE4ODg3Mg@@._V1_SX300.jpg','USA','Comedy, Drama, Romance','Walter Kirn (novel), Jason Reitman (screenplay), Sheldon Turner (screenplay)');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (47,'N/A','N/A','N/A',5.9,'191','62 min','English','PASSED','Monogram','09 Sep 1940','tt0033214','A none-too-popular (nor good) radio singer, Rita Wilson is murdered while singing on the air in a radio studio. Radio page boy, Frankie Ryan, and his janitor pal, Jeff, solve the mystery ...','Howard Bretherton','Up in the Air','Frankie Darro, Marjorie Reynolds, Mantan Moreland, Gordon Jones','True','movie','N/A',NULL,1940,'https://images-na.ssl-images-amazon.com/images/M/MV5BMTYyNjkwMDg2Nl5BMl5BanBnXkFtZTcwMTQ3NzMyMQ@@._V1_SX300.jpg','USA','Action, Comedy, Music','Edmond Kelso (screen play), Edmond Kelso (original story)');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (48,'N/A','N/A','N/A',8.1,'109','8 min','English','N/A','N/A','19 Apr 2013','tt3438666','N/A','Jared Leto','30 Seconds to Mars: Up in the Air','Jared Leto, Shannon Leto, Tomo Milicevic, Nea Dune','True','movie','1 win & 4 nominations.',NULL,2013,'N/A','USA','Short, Music','N/A');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (49,'N/A','$83,775,048','http://www.TheUpInTheAirMovie.com/',7.2,'70','N/A','English','N/A','Paramount Pictures','04 Apr 2009','tt1401642','The arrival of his estranged wife leaves a navy pilot questioning whether or not he can forgive the mother of his children for the broken hearts she has left behind. Even advice from his closest friend still leaves the pilot up in the air.','Wes Llewellyn','Up in the Air','Lonnie Colón, Shannon Cunningham, Melissa Disney, Doug Folsom','True','movie','N/A',NULL,2009,'N/A','USA','Short, Drama','Wes Llewellyn');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (50,'82','$257,704,099','http://www.startrekmovie.com/',8.0,'555,069','127 min','English','PG-13','IMAX','08 May 2009','tt0796366','The brash James T. Kirk tries to live up to his father''s legacy with Mr. Spock keeping him in check as a vengeful Romulan from the future creates black holes to destroy the Federation one planet at a time.','J.J. Abrams','Star Trek','Chris Pine, Zachary Quinto, Leonard Nimoy, Eric Bana','True','movie','Won 1 Oscar. Another 23 wins & 92 nominations.',NULL,2009,'https://m.media-amazon.com/images/M/MV5BMjE5NDQ5OTE4Ml5BMl5BanBnXkFtZTcwOTE3NDIzMw@@._V1_SX300.jpg','USA, Germany','Action, Adventure, Sci-Fi','Roberto Orci, Alex Kurtzman, Gene Roddenberry (television series "Star Trek")');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (51,'72','$228,756,232','http://www.startrekmovie.com/',7.7,'443,815','132 min','English, Klingon','PG-13','Paramount','16 May 2013','tt1408101','After the crew of the Enterprise find an unstoppable force of terror from within their own organization, Captain Kirk leads a manhunt to a war-zone world to capture a one-man weapon of mass destruction.','J.J. Abrams','Star Trek Into Darkness','Chris Pine, Zachary Quinto, Zoe Saldana, Karl Urban','True','movie','Nominated for 1 Oscar. Another 6 wins & 56 nominations.',NULL,2013,'https://m.media-amazon.com/images/M/MV5BMTk2NzczOTgxNF5BMl5BanBnXkFtZTcwODQ5ODczOQ@@._V1_SX300.jpg','USA','Action, Adventure, Sci-Fi','Roberto Orci, Alex Kurtzman, Damon Lindelof, Gene Roddenberry (television series "Star Trek")');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (52,'68','$158,804,470','http://www.startrekmovie.com/',7.1,'208,362','122 min','English','PG-13','Paramount Pictures','22 Jul 2016','tt2660888','The crew of the USS Enterprise explores the furthest reaches of uncharted space, where they encounter a new ruthless enemy, who puts them, and everything the Federation stands for, to the test.','Justin Lin','Star Trek Beyond','Chris Pine, Zachary Quinto, Karl Urban, Zoe Saldana','True','movie','Nominated for 1 Oscar. Another 3 wins & 27 nominations.',NULL,2016,'https://m.media-amazon.com/images/M/MV5BZDRiOGE5ZTctOWIxOS00MWQwLThlMDYtNWIwMDQwNzBjZDY1XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg','USA, China, United Arab Emirates, Canada','Action, Adventure, Sci-Fi, Thriller','Simon Pegg, Doug Jung, Gene Roddenberry (based upon "Star Trek" created by)');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (53,'71','N/A','N/A',7.6,'109,716','111 min','English','PG-13','Paramount Pictures','22 Nov 1996','tt0117731','The Borg travel back in time intent on preventing Earth''s first contact with an alien species. Captain Picard and his crew pursue them to ensure that Zefram Cochran makes his maiden flight reaching warp speed.','Jonathan Frakes','Star Trek: First Contact','Patrick Stewart, Jonathan Frakes, Brent Spiner, LeVar Burton','True','movie','Nominated for 1 Oscar. Another 8 wins & 20 nominations.',NULL,1996,'https://m.media-amazon.com/images/M/MV5BYTllZjRkY2QtYTJlMy00ZTMxLWE0YWQtMWMwYzY2YTM3YzRjXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg','USA','Action, Adventure, Drama, Sci-Fi, Thriller','Gene Roddenberry (television series Star Trek), Rick Berman (story), Brannon Braga (story), Ronald D. Moore (story), Brannon Braga (screenplay), Ronald D. Moore (screenplay)');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (54,'67','N/A','N/A',7.7,'104,386','113 min','English','PG','Paramount Pictures','04 Jun 1982','tt0084726','With the assistance of the Enterprise crew, Admiral Kirk must stop an old nemesis, Khan Noonien Singh, from using the life-generating Genesis Device as the ultimate weapon.','Nicholas Meyer','Star Trek II: The Wrath of Khan','William Shatner, Leonard Nimoy, DeForest Kelley, James Doohan','True','movie','3 wins & 9 nominations.',NULL,1982,'https://m.media-amazon.com/images/M/MV5BMzcyYWE5YmQtNDE1Yi00ZjlmLWFlZTAtMzRjODBiYjM3OTA3XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg','USA','Action, Adventure, Sci-Fi','Gene Roddenberry (based on "Star Trek" created by), Harve Bennett (story), Jack B. Sowards (story), Jack B. Sowards (screenplay)');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (55,'48','N/A','N/A',6.4,'74,264','132 min','English, Klingon','G','Paramount Home Video','08 Dec 1979','tt0079945','When an alien spacecraft of enormous power is spotted approaching Earth, Admiral James T. Kirk resumes command of the overhauled USS Enterprise in order to intercept it.','Robert Wise','Star Trek: The Motion Picture','William Shatner, Leonard Nimoy, DeForest Kelley, James Doohan','True','movie','Nominated for 3 Oscars. Another 4 wins & 16 nominations.',NULL,1979,'https://m.media-amazon.com/images/M/MV5BNzNlMzNlNmQtNmYzNS00YmU5LWIzYWQtMDRkYzIzNzEzOTIyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg','USA','Adventure, Mystery, Sci-Fi','Gene Roddenberry (based on "Star Trek" created by), Harold Livingston (screenplay), Alan Dean Foster (story)');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (56,'71','N/A','N/A',7.3,'71,996','119 min','English, Finnish','PG','Paramount Pictures','26 Nov 1986','tt0092007','To save Earth from an alien probe, Admiral James T. Kirk and his fugitive crew go back in time to San Francisco in 1986 to retrieve the only beings who can communicate with it: humpback whales.','Leonard Nimoy','Star Trek IV: The Voyage Home','William Shatner, Leonard Nimoy, DeForest Kelley, James Doohan','True','movie','Nominated for 4 Oscars. Another 4 wins & 13 nominations.',NULL,1986,'https://m.media-amazon.com/images/M/MV5BMGY2MDE2MGQtMjczYi00YTdhLWIzNzktNDk2NzMzZmYwMTJjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg','USA','Adventure, Comedy, Sci-Fi','Gene Roddenberry (based on "Star Trek" created by), Leonard Nimoy (story), Harve Bennett (story), Steve Meerson (screenplay), Peter Krikes (screenplay), Harve Bennett (screenplay), Nicholas Meyer (screenplay)');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (57,'55','N/A','N/A',6.6,'69,811','118 min','English, Klingon','PG','Paramount Pictures','18 Nov 1994','tt0111280','With the help of long presumed dead Captain Kirk, Captain Picard must stop a renegade scientist willing to murder on a planetary scale in order to enter a space matrix.','David Carson','Star Trek: Generations','Patrick Stewart, Jonathan Frakes, Brent Spiner, LeVar Burton','True','movie','2 wins & 4 nominations.',NULL,1994,'https://m.media-amazon.com/images/M/MV5BNjFiMzc4YzAtNGMzYS00NjI0LWJhYTYtN2JiOTI2ODczYzE3XkEyXkFqcGdeQXVyNTUyMzE4Mzg@._V1_SX300.jpg','USA','Action, Adventure, Mystery, Sci-Fi, Thriller','Gene Roddenberry (television series Star Trek), Rick Berman (story), Ronald D. Moore (story), Brannon Braga (story), Ronald D. Moore (screenplay), Brannon Braga (screenplay)');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (58,'56','N/A','N/A',6.7,'68,253','105 min','English, Klingon, Russian, French','PG','Paramount Pictures','01 Jun 1984','tt0088170','Admiral Kirk and his bridge crew risk their careers stealing the decommissioned Enterprise to return to the restricted Genesis Planet to recover Spock''s body.','Leonard Nimoy','Star Trek III: The Search for Spock','William Shatner, Leonard Nimoy, DeForest Kelley, James Doohan','True','movie','1 win & 7 nominations.',NULL,1984,'https://m.media-amazon.com/images/M/MV5BMTliZGVjZmMtNzEzMy00MzVhLWFhYjYtNDhlYmViNGNiMGFlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg','USA','Action, Adventure, Sci-Fi','Gene Roddenberry (based on "Star Trek" created by), Harve Bennett');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (59,'78','N/A','N/A',7.8,'188,562','88 min','English','PG','Paramount Pictures','02 Jul 1980','tt0080339','A man afraid to fly must ensure that a plane lands safely after the pilots become sick.','Jim Abrahams, David Zucker, Jerry Zucker','Airplane!','Kareem Abdul-Jabbar, Lloyd Bridges, Peter Graves, Julie Hagerty','True','movie','Nominated for 1 Golden Globe. Another 2 wins & 6 nominations.',NULL,1980,'https://m.media-amazon.com/images/M/MV5BZjA3YjdhMWEtYjc2Ni00YzVlLWI0MTUtMGZmNTJjNmU0Yzk2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg','USA','Comedy','Jim Abrahams (written for the screen by), David Zucker (written for the screen by), Jerry Zucker (written for the screen by)');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (60,'48','N/A','N/A',6.1,'44,441','85 min','English','PG','Paramount Home Video','10 Dec 1982','tt0083530','A faulty computer causes a passenger space shuttle to head straight for the Sun. Can Ted Striker save the day and get the shuttle back on track - again?','Ken Finkleman','Airplane II: The Sequel','Lloyd Bridges, Raymond Burr, Chuck Connors, Rip Torn','True','movie','N/A',NULL,1982,'https://m.media-amazon.com/images/M/MV5BMmVkYjg2MDUtN2ExNi00N2QzLTliOWYtMjAzYWNlYjQ1MWZjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg','USA','Comedy, Sci-Fi','Ken Finkleman');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (61,'N/A','N/A','http://www.theasylum.cc/product.php?id=243',2.7,'1,665','91 min','English','TV-14','The Asylum','28 Mar 2014','tt3417334','When a commercial airliner is trapped within a ring of erupting volcanoes, the passengers and crew must find a way to survive - without landing, but, when the relentless onslaught of lava ...','James Kondelik, Jon Kondelik','Airplane vs. Volcano','Dean Cain, Robin Givens, Tamara Goodwin, Matt Mercer','True','movie','N/A',NULL,2014,'https://m.media-amazon.com/images/M/MV5BMTQyMzE1MzI4OF5BMl5BanBnXkFtZTgwMTcyMTA1MTE@._V1_SX300.jpg','USA','Action, Adventure, Drama, Sci-Fi, Thriller','James Kondelik (screenplay), Jon Kondelik (screenplay)');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (62,'N/A','N/A','N/A',7.9,'108','81 min','English','N/A','N/A','20 Jul 2004','tt0427256','Thirteen classic perfomances by Rock and Roll Hall of Fame band Jefferson Airplane, augmented by orginal interviews with the band members and photographs by famed photographer Jim Marshall.','Bob Sarles','Fly Jefferson Airplane','Signe Anderson, Marty Balin, Jack Casady, Joey Covington','True','movie','N/A',NULL,2004,'https://images-na.ssl-images-amazon.com/images/M/MV5BMTIxNTU1MjU2MV5BMl5BanBnXkFtZTcwODE3MTcyMQ@@._V1_SX300.jpg','USA','Music','N/A');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (63,'N/A','N/A','N/A',7.3,'54','7 min','Russian','N/A','N/A','27 Feb 2013','tt3652586','A young boy imagines his mother to be an airplane who travels to exotic lands.','Yulia Aronova','My Mom Is an Airplane!','N/A','True','movie','1 win & 2 nominations.',NULL,2013,'https://m.media-amazon.com/images/M/MV5BYWE3MDQ0NjktZGE3Yy00ZGQ3LWJkZDctZjVkNTFjMGU3YjhiXkEyXkFqcGdeQXVyMzU3MDU3NjI@._V1_SX300.jpg','USA, Russia','Animation, Short, Family','N/A');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (64,'N/A','N/A','N/A',4.8,'39','100 min','French','N/A','N/A','23 Jan 2002','tt0301125','N/A','Marie-France Pisier','Like an Airplane','Bérénice Bejo, Marie-France Pisier, Guillaume Depardieu, Clément van den Bergh','True','movie','N/A',NULL,2002,'N/A','France','Biography, Drama','Pascal Bonitzer, Marie-France Pisier');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (65,'N/A','N/A','N/A',8.0,'38','100 min','English','N/A','N/A','10 Dec 1971','tt0067220','Two pilots are hired to reclaim a stolen jet from the son of a South American dictator.','Leslie H. Martinson','How to Steal an Airplane','Pete Duel, Clinton Greyn, Sal Mineo, Claudine Longet','True','movie','N/A',NULL,1971,'N/A','USA','Adventure','Philip DeGuere Jr., Robert Foster');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (66,'N/A','N/A','N/A',8.7,'29','100 min','English','N/A','N/A','01 Jun 2006','tt1094159','An experimental drama detailing the post 9/ll life of a successful musician who tries to rescue his floundering relationship by reinventing himself, but has lost his ability to communicate beyond his own vanity.','Zach Horton','Airplane Disasters','Joshua Fisher P. Anderson, Monica Young, Maria-Elena Laas, Zach Horton','True','movie','N/A',NULL,2006,'https://images-na.ssl-images-amazon.com/images/M/MV5BMTY4OTI5NDQxN15BMl5BanBnXkFtZTcwMTAxMTU1MQ@@._V1_SX300.jpg','USA','Drama','Zach Horton');
INSERT INTO reviews(movieId,metascore,boxOffice,website,imdbRating,imdbVotes,runtime,language,rated,production,released,imdbid,plot,director,title,actors,response,type,awards,dvd,year,poster,country,genre,writer) VALUES (238,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'*** THIS IS A MOVIE IN MYSQL ***',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

COMMIT WORK;